code --install-extension abhiagr.logcat
code --install-extension amlovey.shaderlabvscodefree
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension donjayamanne.githistory
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension felipecaputo.git-project-manager
code --install-extension johnpapa.winteriscoming
code --install-extension k--kato.docomment
code --install-extension karyfoundation.theme-karyfoundation-themes
code --install-extension liviuschera.noctis
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension perragnaredin.light-plus-tweaked
code --install-extension PKief.material-icon-theme
code --install-extension sdras.night-owl
code --install-extension slevesque.shader
code --install-extension smockle.xcode-default-theme
code --install-extension Tobiah.unity-tools
code --install-extension uloco.theme-bluloco-dark
code --install-extension uloco.theme-bluloco-light
code --install-extension Unity.unity-debug
